config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'

  resources :events

  get '/profile' => 'users#profile', as: 'profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, :event_date, presence: true
  validates :repeat, inclusion: { in: 0..4 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html
  expose(:events) { Event.all.decorate }
  expose_decorated :event

  before_action :authenticate_user!, except: :index

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    current_user.events << event

    event.save
    respond_with event
  end

  def update
    event.update(event_params)
    respond_with event
  end

  def destroy
    event.destroy
    respond_with event
  end

  private

  def event_params
    params.require(:event).permit(:title, :event_date, :repeat)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user) { current_user }
  expose_decorated :events, from: :user

  before_action :authenticate_user!

  def profile; end
end

app/views/events/_form.html.slim
= form_with(model: event, local: true) do |f|
  - if event.errors.any?
    #error_explanation
      h2
        = pluralize(event.errors.count, "error")
        | prohibited this event from being saved:
      ul
        - event.errors.full_messages.each do |message|
          li= message
  .field
    = f.label t('Title')
    = f.text_field :title
  .field
    = f.label t('Event date')
    = f.date_select :event_date, start_year: Date.today.year, end_year: Date.today.year + 20
  .field
    = f.label t('Repeat')
    = f.select :repeat, options_for_select([[t("every_day"), 0], [t("every_week"), 1], [t("every_month"), 2], [t("every_year"), 3]])
  .actions
    = f.submit t('.accept_button'), class: "expanded button"

app/views/events/edit.html.slim
h3= t'.edit_event_message'
= render 'form', event: event
= link_to t('.delete_button'), event, method: :delete, data: { confirm: t('confirm')}, class:"expanded alert button"
= link_to t('Back'), profile_path, class: "expanded hollow button"

app/views/events/index.html.slim
div= link_to t('.profile_button'), profile_path
h3
  = t('.calendar_of_events_message')
table
  thead
    tr
      th= t'Title'
      th= t'Event date'
      th= t'Repeat'
      th= t'Author'
  tbody
    - events.each do |event|
      tr
        td= link_to event.title, event
        td= event.event_date
        td= event.translated_repeat
        td= event.user.email
= link_to t('.new_event_button'), new_event_path, class:"button expanded"

app/views/events/new.html.slim
h3= t'.new_event_message'
= render 'form', event: event
= link_to t('Back'), events_path, class:"expanded hollow button"

app/views/events/show.html.slim
.card
  div clas="card-section" 
    p
      strong
        = t'Title'
        | :
      = event.title
    p
      strong
        = t'Event date'
        | :
      = event.event_date
    p
      strong
        = t'Repeat'
        | :
      = event.translated_repeat
    p
      strong
        = t'Author'
        | :
      = event.user.email
= link_to t('Back'), events_path, class: "expanded hollow button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Calendar" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="block">

      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>

      <%= yield %>
      <div class="lang_buttons">
        <%= link_to("ru", locale: :ru )%> |
        <%= link_to("en", locale: :en )%>
      </div>
    </div>
    
  </body>
</html>

app/views/users/profile.html.slim
h3= t('profile.title')
div
  strong email:
  = user.email
  | | 
  = link_to t('Edit'), edit_user_registration_url
  = link_to t('Logout'), destroy_user_session_url, method: "delete"
br/
div
  = t('profile.my_events_message')
  .events_list
    table
      thead
        tr
          th= t'Title'
          th= t'Event date'
          th= t'Repeat'
      tbody
        - events.each do |event|
          tr
            td= link_to "#{event.title} (#{t('Edit')} )", edit_event_path(event)
            td= event.event_date
            td= event.translated_repeat
    = link_to t('profile.new_event_button'), new_event_path, class:"expanded button"
    = link_to t('profile.all_events_button'), events_path, class:"expanded button"